"""
WebSocket: /ws/alerts
Push notification channel for real-time safety alerts (intrusion detection, etc.).
Connected clients receive alerts the moment they are generated by the sensor layer.
"""

import asyncio
import json
import logging
from typing import Set

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

router = APIRouter(tags=["WebSocket"])
logger = logging.getLogger(__name__)

# Active subscriber connections
_subscribers: Set[WebSocket] = set()


async def broadcast_alert(alert: dict) -> None:
    """
    Broadcast a new alert to all connected WebSocket clients.
    Call this from any sensor/AI integration that detects an intrusion.

    Example:
        from ws_handlers.alerts_ws import broadcast_alert
        await broadcast_alert({
            "id": "ALT-999",
            "title": "Motion Detected",
            "severity": "DANGER",
            ...
        })
    """
    dead: Set[WebSocket] = set()
    message = json.dumps(alert)

    for ws in _subscribers:
        try:
            await ws.send_text(message)
        except Exception:
            dead.add(ws)

    _subscribers -= dead


@router.websocket("/ws/alerts")
async def alerts_ws(websocket: WebSocket):
    """
    Persistent push channel — the app listens here for live safety alerts.
    Server sends a heartbeat every 30 s to keep the connection alive through
    NAT / mobile network timeouts.
    """
    await websocket.accept()
    _subscribers.add(websocket)
    logger.info("Alerts WS connected  total=%d", len(_subscribers))

    try:
        while True:
            # Heartbeat keeps NAT / mobile connections alive
            await asyncio.sleep(30)
            await websocket.send_text(json.dumps({"type": "heartbeat"}))
    except WebSocketDisconnect:
        logger.info("Alerts WS disconnected")
    except Exception as exc:
        logger.error("Alerts WS error: %s", exc)
    finally:
        _subscribers.discard(websocket)
