"""
WebSocket: /ws/alerts
Push notification channel for real-time safety alerts (intrusion detection, etc.).
Connected clients receive alerts the moment they are generated by the sensor layer.
"""

import asyncio
import json
import logging
from typing import Set

from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from services.connection_manager import connection_manager
import asyncio
import json
import logging

router = APIRouter(tags=["WebSocket"])
logger = logging.getLogger(__name__)

async def broadcast_alert(alert: dict) -> None:
    """
    Broadcast a new alert to all connected WebSocket clients.
    """
    message = json.dumps(alert)
    # Phase 1: Use connection_manager to broadcast to all users
    await connection_manager.broadcast({"event": "alert", "data": alert})

@router.websocket("/ws/alerts")
async def alerts_ws(websocket: WebSocket):
    """
    Persistent push channel — the app listens here for live safety alerts.
    """
    await connection_manager.connect(websocket, role="USER")
    logger.info("Alerts WS connected")

    try:
        while True:
            # Heartbeat keeps NAT / mobile connections alive
            await asyncio.sleep(30)
            await websocket.send_text(json.dumps({"type": "heartbeat"}))
    except WebSocketDisconnect:
        logger.info("Alerts WS disconnected")
    except Exception as exc:
        logger.error("Alerts WS error: %s", exc)
    finally:
        connection_manager.disconnect(websocket)
